from tkinter import *

# Window set up---------------------------------------------------------------------------------------------------------
window = Tk()
window.geometry("500x500")
window.title("Matrix Calculator")

# Matrix inputs---------------------------------------------------------------------------------------------------------
A = Label(window, text='A =', font=('Cambria Math', 14, 'italic'))

A1 = Entry(window, width=3, font=('Helvetica', 11))
A2 = Entry(window, width=3, font=('Helvetica', 11))
A3 = Entry(window, width=3, font=('Helvetica', 11))
A4 = Entry(window, width=3, font=('Helvetica', 11))
A5 = Entry(window, width=3, font=('Helvetica', 11))
A6 = Entry(window, width=3, font=('Helvetica', 11))
A7 = Entry(window, width=3, font=('Helvetica', 11))
A8 = Entry(window, width=3, font=('Helvetica', 11))
A9 = Entry(window, width=3, font=('Helvetica', 11))
A10 = Entry(window, width=3, font=('Helvetica', 11))
A11 = Entry(window, width=3, font=('Helvetica', 11))
A12 = Entry(window, width=3, font=('Helvetica', 11))
A13 = Entry(window, width=3, font=('Helvetica', 11))
A14 = Entry(window, width=3, font=('Helvetica', 11))
A15 = Entry(window, width=3, font=('Helvetica', 11))
A16 = Entry(window, width=3, font=('Helvetica', 11))
A17 = Entry(window, width=3, font=('Helvetica', 11))
A18 = Entry(window, width=3, font=('Helvetica', 11))
A19 = Entry(window, width=3, font=('Helvetica', 11))
A20 = Entry(window, width=3, font=('Helvetica', 11))
A21 = Entry(window, width=3, font=('Helvetica', 11))
A22 = Entry(window, width=3, font=('Helvetica', 11))
A23 = Entry(window, width=3, font=('Helvetica', 11))
A24 = Entry(window, width=3, font=('Helvetica', 11))
A25 = Entry(window, width=3, font=('Helvetica', 11))

A1.insert(0, "X")
A2.insert(0, "X")
A3.insert(0, "X")
A4.insert(0, "X")
A5.insert(0, "X")
A6.insert(0, "X")
A7.insert(0, "X")
A8.insert(0, "X")
A9.insert(0, "X")
A10.insert(0, "X")
A11.insert(0, "X")
A12.insert(0, "X")
A13.insert(0, "X")
A14.insert(0, "X")
A15.insert(0, "X")
A16.insert(0, "X")
A17.insert(0, "X")
A18.insert(0, "X")
A19.insert(0, "X")
A20.insert(0, "X")
A21.insert(0, "X")
A22.insert(0, "X")
A23.insert(0, "X")
A24.insert(0, "X")
A25.insert(0, "X")

B = Label(window, text='B =', font=('Cambria Math', 14, 'italic'))

B1 = Entry(window, width=3, font=('Helvetica', 11))
B2 = Entry(window, width=3, font=('Helvetica', 11))
B3 = Entry(window, width=3, font=('Helvetica', 11))
B4 = Entry(window, width=3, font=('Helvetica', 11))
B5 = Entry(window, width=3, font=('Helvetica', 11))
B6 = Entry(window, width=3, font=('Helvetica', 11))
B7 = Entry(window, width=3, font=('Helvetica', 11))
B8 = Entry(window, width=3, font=('Helvetica', 11))
B9 = Entry(window, width=3, font=('Helvetica', 11))
B10 = Entry(window, width=3, font=('Helvetica', 11))
B11 = Entry(window, width=3, font=('Helvetica', 11))
B12 = Entry(window, width=3, font=('Helvetica', 11))
B13 = Entry(window, width=3, font=('Helvetica', 11))
B14 = Entry(window, width=3, font=('Helvetica', 11))
B15 = Entry(window, width=3, font=('Helvetica', 11))
B16 = Entry(window, width=3, font=('Helvetica', 11))
B17 = Entry(window, width=3, font=('Helvetica', 11))
B18 = Entry(window, width=3, font=('Helvetica', 11))
B19 = Entry(window, width=3, font=('Helvetica', 11))
B20 = Entry(window, width=3, font=('Helvetica', 11))
B21 = Entry(window, width=3, font=('Helvetica', 11))
B22 = Entry(window, width=3, font=('Helvetica', 11))
B23 = Entry(window, width=3, font=('Helvetica', 11))
B24 = Entry(window, width=3, font=('Helvetica', 11))
B25 = Entry(window, width=3, font=('Helvetica', 11))

B1.insert(0, "X")
B2.insert(0, "X")
B3.insert(0, "X")
B4.insert(0, "X")
B5.insert(0, "X")
B6.insert(0, "X")
B7.insert(0, "X")
B8.insert(0, "X")
B9.insert(0, "X")
B10.insert(0, "X")
B11.insert(0, "X")
B12.insert(0, "X")
B13.insert(0, "X")
B14.insert(0, "X")
B15.insert(0, "X")
B16.insert(0, "X")
B17.insert(0, "X")
B18.insert(0, "X")
B19.insert(0, "X")
B20.insert(0, "X")
B21.insert(0, "X")
B22.insert(0, "X")
B23.insert(0, "X")
B24.insert(0, "X")
B25.insert(0, "X")

# Buttons---------------------------------------------------------------------------------------------------------------
generate = Button(window, text='Generate', font=('Arial', 15))
add = Button(window, text=' + ', font=('Arial', 15))
subtract = Button(window, text=' - ', font=('Arial', 15))
multiply = Button(window, text=' x ', font=('Arial', 15))

# GUI set up------------------------------------------------------------------------------------------------------------
title = Label(window, text='Matrix Calculator', font=('Cambria Math', 20, 'bold'))

# Griding---------------------------------------------------------------------------------------------------------------
title.grid(row=0, columnspan=10)
A.grid(row=1, column=0)
A1.grid(row=1, column=1)
B.grid(row=1, column=2)
B1.grid(row=1, column=3)
generate.grid(row=5, column=0)
add.grid(row=5, column=1)
subtract.grid(row=5, column=2)
multiply.grid(row=5, column=3)

window.mainloop()
